export const SIGNIN_AZURE_USER_REQUEST = 'SIGNIN_AZURE_USER_REQUEST';
export const SIGNIN_AZURE_USER_SUCCESS = 'SIGNIN_AZURE_USER_SUCCESS';
export const SIGNIN_AZURE_USER_FAILURE = 'SIGNIN_AZURE_USER_FAILURE';
